workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 60
    # если проект в корне — оставь ".", иначе укажи путь к модулю/папке проекта
    working_directory: .

    environment:
      java: 17
      vars:
        GRADLE_TASK: "assembleRelease"

    scripts:
      - name: Clean
        script: ./gradlew clean
      - name: Build
        script: ./gradlew $GRADLE_TASK

    artifacts:
      - app/build/outputs/**/*.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
